apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-token-refresh
  namespace: app-blue
spec:
  schedule: "0 */8 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: default
          containers:
          - name: ecr-token-refresh
            image: odaniait/aws-kubectl:latest
            command:
            - /bin/sh
            - -c
            - |
              TOKEN=$(aws ecr get-login-password --region us-east-1)
              kubectl delete secret regcred -n app-blue --ignore-not-found
              kubectl create secret docker-registry regcred \
                --docker-server=692531238663.dkr.ecr.us-east-1.amazonaws.com \
                --docker-username=AWS \
                --docker-password="${TOKEN}" \
                -n app-blue
          restartPolicy: OnFailure