apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-advanced-app-rollout
  namespace: app-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-advanced-app
  template:
    metadata:
      labels:
        app: my-advanced-app
    spec:
      # Use the secret we created to authenticate with AWS ECR
      imagePullSecrets:
      - name: regcred
      containers:
      - name: my-app
        # Corrected image URI for ap-south-1 region
        image: 692531238663.dkr.ecr.ap-south-1.amazonaws.com/my-advanced-app:v1
        ports:
        - containerPort: 80
  strategy:
    blueGreen: 
      activeService: my-advanced-app-service
      previewService: my-advanced-app-preview-service
      autoPromotionEnabled: false